name: Flutter + Native C++ debug APK

on:
  push:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Flutter + native C++ debug APK
        run: |
          docker run --rm \
            -v "$PWD/demo":/app \
            -w /app \
            instrumentisto/flutter \
            flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: demo-debug-apk
          path: demo/build/app/outputs/flutter-apk/app-debug.apk
